// This file is generated by Supabase tooling.
// We guard against missing Vite env vars so production deploys don't crash.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY;

export function getSupabaseEnvError() {
  const missing: string[] = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY)
    missing.push('VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)');
  if (missing.length === 0) return null;

  return (
    `Supabase env vars are missing: ${missing.join(', ')}. ` +
    `For Vite apps, these must be set in your deployment and available during ` +
    `the build (they are read from import.meta.env).`
  );
}

let supabase: SupabaseClient<Database> | null = null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
try {
  if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }
} catch (e) {
  // Prevent module import crash; components will handle `supabase === null`.
  console.error('Failed to initialize Supabase client:', e);
}

export { supabase };